Add iati.fetch.get_publishers
IATI/iati.fetch pull request #12
Opened 2017-06-28 09:14 UTC by dalepotter

Add function to get a list of publishers who are publishing to the IATI Registry.

2017-07-06 12:37 UTC, allthatilk requested changes
A couple minor changes, main one for mock URL layout to keep it consistent with get_dataset

2017-07-06 12:37 UTC, allthatilk commented on iati/fetch/__init__.py
> +    """
Add Todo for replacing is_response_okay method.

2017-07-06 12:37 UTC, allthatilk commented on iati/fetch/tests/test_dataset.py
> +        mock_publishers_url = 'http://test.com/publishers'
Have a look at changes to the TestDataset tests and extracting the mock URL to keep things DRY.

2017-07-06 12:57 UTC, dalepotter commented
Thanks for the review - will look to fix these issues outside of project time. Hopefully tomorrow.

2017-07-12 16:25 UTC, dalepotter commented on iati/fetch/__init__.py
> +    """
On reflection I think it's ok to not include a todo here. 

There is already a todo in the `is_response_okay` docstring. Also, when the function is removed all usage of the function should be replaced anyway.

2017-07-12 16:38 UTC, dalepotter commented on iati/fetch/tests/test_dataset.py
> +        mock_publishers_url = 'http://test.com/publishers'
I've made some changes in 655ba00 - is this what you mean?

2017-07-21 15:17 UTC, allthatilk commented on iati/fetch/__init__.py
> +    """
Cool beans!

2017-07-21 15:17 UTC, allthatilk approved these changes

2017-07-21 15:18 UTC, merged